int _putchar(char c);
void _puts_recursion(char *s);
void _print_rev_recursion(char *s);
int _strlen_recursion(char *s);
int factorial(int n);
int _pow_recursion(int x, int y);
int _sqrt_recursion(int n);
int _sqrt_helper(int n, int g);
int is_prime_number(int n);
int prime_helper(int n, int i);
int is_palindrome(char *s);
int palindrome_helper(char *s, int i, int j);
int wildcmp(char *s1, char *s2);
